### ISSUE TITLE
cURL error 7: Failed to connect to rest.nexmo.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by jameslouies11** [Nexmo/nexmo-laravel#28]
I'm currently making sms verification code that sends after the user reserves in my system. It's working fine in my localhost but when I uploaded it on hostinger, this error comes out. When I submit, it loads very long then pops out that error. How could I fix this?

**Comment by lornajane** [comment]
That error 7 indicates that your code couldn't connect, and the long delay could mean a DNS problem or some other timeout. Since it works correctly on your development platform, I'm not sure it's a bug with the library. I recommend you contact your hosting provider and check that they have the same version of PHP as you use on your development platform (localhost) and ask if there's any particular configuration needed (such as a proxy) to make outgoing requests from your code.

**Comment by lornajane** [comment]
Closing after no further update was received
